language: rust

cache: cargo

rust:
  - nightly
  - beta
  - stable
  - 1.2.0

env:
  matrix:
    - FEATURES=''
    - FEATURES='--features "regexp regexp_macros" '
    - FEATURES='--features "regexp regexp_macros verbose-errors" '

before_script:
  - if [ "$TRAVIS_RUST_VERSION" != "1.2.0" ]; then
      cargo install cargo-travis --force && export PATH=$HOME/.cargo/bin:$PATH;
    fi

script:
  - '[ $TRAVIS_RUST_VERSION != 1.2.0   ] || cargo test --verbose --features "regexp"'
  - '[ $TRAVIS_RUST_VERSION != nightly ] || cargo build --verbose --no-default-features'
  - '[ $TRAVIS_RUST_VERSION == 1.2.0   ] || eval cargo test --verbose $FEATURES'
  - '[ $TRAVIS_RUST_VERSION != nightly ] || cargo bench --verbose'
  - '[ $TRAVIS_RUST_VERSION != stable  ] || cargo doc --verbose --features "std regexp regexp_macros" --no-default-features'

after_success:
  - '[ $TRAVIS_RUST_VERSION != nightly ] || cargo bench --verbose'
  - '[ $TRAVIS_RUST_VERSION == 1.2.0   ] || cargo coveralls --verbose'
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" != "master" ] && [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install cargo-benchcmp --force;
        cargo bench > benches-variable;
        git fetch;
        git checkout master;
        cargo bench > benches-control;
        cargo benchcmp benches-control benches-variable;
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9c035a194ac4fd4cc061
    on_success: change
    on_failure: always
    on_start: false

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
