language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly
  - beta
  - stable
  - 1.2.0

env:
  - FEATURES="--features \"regexp regexp_macros\""
  - FEATURES="--features \"stream regexp regexp_macros\""
  - FEATURES="--features \"stream regexp regexp_macros\" --no-default-features"

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo --only 1.2     test  -- --features regexp
  - travis-cargo --only nightly build -- --features "nightly core regexp"

  - echo $FEATURES && travis-cargo test  -- $FEATURES
  - travis-cargo bench
  - travis-cargo --only stable doc -- --features "stream regexp regexp_macros" --no-default-features

matrix:
  exclude:
  - rust: 1.2
    env: FEATURES="--features \"regexp regexp_macros\""
  - rust: 1.2
    env: FEATURES="--features \"stream regexp regexp_macros\""
  - rust: 1.2
    env: FEATURES="--features \"stream regexp regexp_macros\" --no-default-features"

after_success:
  - travis-cargo bench
  - travis-cargo coveralls --no-sudo

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9c035a194ac4fd4cc061
    on_success: change
    on_failure: always
    on_start: false


env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

sudo: false
